### ISSUE TITLE
Up - Down - Left - Right not working

### ISSUE THREAD

**Issue by Ademking** [ArthurBeaulieu/Shortcut.js#1]

**Comment by ArthurBeaulieu** [comment]
Have you tried with ArrowLeft, ArrowRight, ArrowUp or ArrowDown, as these are the value used in event.key ? Let me know if this fix this issue

**Comment by ArthurBeaulieu** [comment]
Ok, you indeed need to put ArrowLeft, ArrowUp, ArrowRight or ArrowDown to register a keyboard event with directionnal arrows. I'll update readme to explain that scenario.

**Comment by ArthurBeaulieu** [comment]
README update pushed in 14b7763 commit. Let me know if you have additionnal questions
